### PR TITLE
Added tests for shiftLeft and shiftRight methods.

### PR DESCRIPTION
**Pull request by git-afsantos**

### CODE REVIEW

**Comment by bsonntag** [comment]
It's just a little hard to read "the quad's second should be equal to the other's third", and so on...

What if you create another quad (named something like "expected") that is equal to the first quad inverted? Then you could just `assertEquals(expected, inverted);`

**Comment by git-afsantos** [comment]
Is something along these lines better? Should I change variable names, for instance?

**Comment by git-afsantos** [comment]
Maybe I should change these tests to match the format of your Quintuple test, using `@Before` and setup variables.

**Comment by git-afsantos** [comment]
I went on and added the missing copyright statement.

**Comment by git-afsantos** [comment]
And fixed the typo. :smile:

**Comment by bsonntag** [comment]
Yes, that's better. :) Using `@Before` is a matter of preference, I think.

Thank you!

Go ahead and merge. :+1:

**Pull request merged**
